Issue 2 relative vendordir
luyadev/luya-composer pull request #5
Opened 2018-06-05 20:57 UTC by boehsermoe

2018-06-06 08:28 UTC, nadar commented
I am not sure if `@vendor` is a good solution, cause if we are once out of application context the path wont work. Why not using relativ paths for both?

2018-06-06 08:30 UTC, nadar commented
Besides: I need time to test, cause when i was working on this it was very hard to have good unit tests or even test the plugin at all. Composer plugins are really hard to test (at least as far as i can see). So maybe they changed this or i need to invest more time in testing.

2018-06-06 18:50 UTC, boehsermoe commented
Ok better relative path too. I will take look to the unit tests and will expend them if necessary.

2018-06-06 20:39 UTC, boehsermoe commented
I refactored and advanced the unit test. I know it is much stuff in `TestCase::setUp` but I took it over from the composer.

2018-06-07 06:48 UTC, nadar approved these changes
Looks good to me at the first sight. I will make some tests and merge afterwards.

2018-07-21 17:28 UTC, nadar commented
(@boehsermoe i am really sorry i had no time to take care on this yet, will do it next week!)

2018-11-13 07:21 UTC, boehsermoe commented
@nadar some weeks ago now 😉

2018-11-13 07:36 UTC, nadar commented
Still in my todo :-) thanks for mention

2018-11-13 07:53 UTC, nadar commented
I will setup travis, but i strongly assume you did run the test successfully and correct of course. In generell, i really had problems with unit testing for composer plugin, this is just a pain (or maybe i did not understand correctly how to test "real word scenarios") - therefore i also created this "how to test" guide section - https://github.com/luyadev/luya-composer#local-testing-for-composer-plugin-development have you used this?

2018-11-13 09:35 UTC, nadar requested changes
I was running the tests locally, they are passing. Travis errors, not sure why. Please add the php docs and missing since tags. Also there is a todo  - maybe we should do the to-do? :-)

Otherwise looks good.

2018-11-13 09:35 UTC, nadar commented on src/Installer.php
> +    public function getRelativeVendorDir()
@boehsermoe please add php docs and since tag.

2018-11-13 09:35 UTC, nadar commented on src/Plugin.php
> +    public $linkPath = 'luya';
please add phpdoc and since tags

2018-11-13 09:35 UTC, nadar commented on src/Plugin.php
> +    public function getRelativeVendorDir(Composer $composer)
Same here: php doc and since tag

2018-11-13 09:35 UTC, nadar commented on tests/LuyaComposerPluginTest.php
> +        // @todo: own test
@boehsermoe what does that mean? So i can not merge unless there is something to do :-)

2018-11-14 07:53 UTC, nadar approved these changes

2018-11-14 07:53 UTC, merged