Cleanup symlink after test
luyadev/luya-composer pull request #6
Opened 2018-11-14 18:07 UTC by boehsermoe

2018-11-14 18:20 UTC, nadar commented
The travis check seems to faile due to a missing file.

2018-11-14 19:14 UTC, boehsermoe commented
I got it fixed... after many try and errors...

2018-11-14 19:47 UTC, nadar requested changes

2018-11-14 19:47 UTC, nadar commented on src/Plugin.php
> +                symlink($this->getRelativeVendorDir($event->getComposer()) . DIRECTORY_SEPARATOR . 'luyadev/luya-core/bin/luya', $this->linkPath);
@boehsermoe the `@` oppresses the exception on windows, see issue in comment above (https://github.com/luyadev/luya/issues/1694)

2018-11-15 08:17 UTC, nadar approved these changes

2018-11-15 08:17 UTC, merged